export const dataExample = [
  {
    id: "1",
    hoTen: "Quan Lê",
    soCMND: "213432412",
    ngaySinh: "13-03-1995",
    tenGioiTinh: "Nam",
    danToc: "Kinh",
    tonGiao: "Thiên chúa",
    quocTich: "Việt Nam",
    tenDoanhNghiep:"Phương Nam smart",
    idLoaiHinh: "1",
    namThanhLap:"14-03-2000",
    vonDieuLe:"200000000000",
    nguoiLienHe:"Nguyễn Văn A",
    chucVuNguoiLienHe:"CEO",
    sdtNguoiLienHe:"09123456789",
    emailNguoiLienHe:"nguyenvana@gmail.com",
    moHinhKinhDoanhs: [
      {
        tenMoHinh: "Mô hình 1",
        tenNganhHang: "Y tế",
        thuongHieu: "Vinasin",
        tuoiTu: 19,
        tuoiDen: 29,
        doiTuongkhachHang: "Nam",
        thuNhapTu: 12000000,
        thuNhapDen: 20000000,
        giaTrungBinhTu: 12000,
        giaTrungBinhDen: 40000,
        tenXuatXu: "Viet Nam",
        noiBatkhacBiet: "Hàng người Việt",
        tenHoSoLoaiHinh: "Hồ Sơ 1",
        tenHoSoXuatXu: "Hoa Kỳ",
        tenHoSoChungMinhNhapKhau: "Hồ Sơ chứng minh 1",
        doanhThuTrungBinhTu: 200000000,
        doanhThuTrungBinhDen: 400000000,
        dienTichToiThieu: 120,
        dienTichToiDa: 440,
        dacDiemViTri: "Ngã Tư",
        kieuGianHang: "Kiểu mặt bằng 1",
        giaThueChapNhan: 20000000,
        tenTienTe: "VND",
        tenViTriCuahang: "Ngã tư Thành Thái",
        soLuongCuaHang: 10,
        cuaHangDaCo: 12,
        cuaHangDuKien: 23,
        viTriQuanTamMoCuaHang: "Không",
        yeuCauDatBiet: "không",
        tenThoiGianThietKeTB: "2 tháng",
        tenThoiGianThiCongTB: "1 tháng",
        yeuCauMarketing: "Không",
      },
    ],
    dienTich: "120km2",
    giaThueDeNghi: "120000000",
    tenTienTe: "VND",
    thoiGianMo: "12-12-2022",
    cacVanDeKhac: "Không",
  },
  {
    id: "2",
    hoTen: "Hà Lê",
    soCMND: "213432432",
    ngaySinh: "13-03-1996",
    tenGioiTinh: "Nữ",
    danToc: "Kinh",
    tonGiao: "Thiên chúa",
    quocTich: "Việt Nam",
    tenDoanhNghiep:"Phương Tây smart",
    idLoaiHinh: "1",
    namThanhLap:"14-03-2000",
    vonDieuLe:"200000000000",
    nguoiLienHe:"Nguyễn Văn B",
    chucVuNguoiLienHe:"CEO",
    sdtNguoiLienHe:"09123456789",
    emailNguoiLienHe:"nguyenvana@gmail.com",
    moHinhKinhDoanhs: [
      {
        tenMoHinh: "Mô hình 2",
        tenNganhHang: "Y tế",
        thuongHieu: "Vinasin",
        tuoiTu: 19,
        tuoiDen: 29,
        doiTuongkhachHang: "Nu",
        thuNhapTu: 12000000,
        thuNhapDen: 20000000,
        giaTrungBinhTu: 12000,
        giaTrungBinhDen: 40000,
        tenXuatXu: "Viet Nam",
        noiBatkhacBiet: "Hàng người Việt",
        tenHoSoLoaiHinh: "Hồ Sơ 1",
        tenHoSoXuatXu: "Hoa Kỳ",
        tenHoSoChungMinhNhapKhau: "Hồ Sơ chứng minh 1",
        doanhThuTrungBinhTu: 200000000,
        doanhThuTrungBinhDen: 400000000,
        dienTichToiThieu: 120,
        dienTichToiDa: 440,
        dacDiemViTri: "Ngã Tư",
        kieuGianHang: "Kiểu mặt bằng 1",
        giaThueChapNhan: 20000000,
        tenTienTe: "VND",
        tenViTriCuahang: "Ngã tư Thành Thái",
        soLuongCuaHang: 10,
        cuaHangDaCo: 12,
        cuaHangDuKien: 23,
        viTriQuanTamMoCuaHang: "Không",
        yeuCauDatBiet: "không",
        tenThoiGianThietKeTB: "3 tháng",
        tenThoiGianThiCongTB: "3 tháng",
        yeuCauMarketing: "Không",
      },
    ],
    dienTich: "120km2",
    giaThueDeNghi: "120000000",
    tenTienTe: "VND",
    thoiGianMo: "12-12-2022",
    cacVanDeKhac: "Không",
  },
  {
    id: "3",
    hoTen: "Trần Dần",
    soCMND: "213432132",
    ngaySinh: "13-03-1996",
    tenGioiTinh: "Nam",
    danToc: "Kinh",
    tonGiao: "Thiên chúa",
    quocTich: "Việt Nam",
    tenDoanhNghiep:"Phương Đông smart",
    idLoaiHinh: "1",
    namThanhLap:"14-03-2000",
    vonDieuLe:"200000000000",
    nguoiLienHe:"Nguyễn Văn C",
    chucVuNguoiLienHe:"CEO",
    sdtNguoiLienHe:"09123456789",
    emailNguoiLienHe:"nguyenvana@gmail.com",
    moHinhKinhDoanhs: [
      {
        tenMoHinh: "Mô hình 2",
        tenNganhHang: "Y tế",
        thuongHieu: "Vinasin",
        tuoiTu: 19,
        tuoiDen: 29,
        doiTuongkhachHang: "Tre em",
        thuNhapTu: 12000000,
        thuNhapDen: 20000000,
        giaTrungBinhTu: 12000,
        giaTrungBinhDen: 40000,
        tenXuatXu: "Viet Nam",
        noiBatkhacBiet: "Hàng người Việt",
        tenHoSoLoaiHinh: "Hồ Sơ 1",
        tenHoSoXuatXu: "Hoa Kỳ",
        tenHoSoChungMinhNhapKhau: "Hồ Sơ chứng minh 1",
        doanhThuTrungBinhTu: 200000000,
        doanhThuTrungBinhDen: 400000000,
        dienTichToiThieu: 120,
        dienTichToiDa: 440,
        dacDiemViTri: "Ngã Tư",
        kieuGianHang: "Kiểu mặt bằng 1",
        giaThueChapNhan: 20000000,
        tenTienTe: "VND",
        tenViTriCuahang: "Ngã tư Thành Thái",
        soLuongCuaHang: 10,
        cuaHangDaCo: 12,
        cuaHangDuKien: 23,
        viTriQuanTamMoCuaHang: "Không",
        yeuCauDatBiet: "không",
        tenThoiGianThietKeTB: "1 tháng",
        tenThoiGianThiCongTB: "3 tháng",
        yeuCauMarketing: "Không",
      },
    ],
    dienTich: "120km2",
    giaThueDeNghi: "120000000",
    tenTienTe: "VND",
    thoiGianMo: "12-12-2022",
    cacVanDeKhac: "Không",
  },
  {
    id: "4",
    hoTen: "Trần Công Lợi",
    soCMND: "223432132",
    ngaySinh: "15-03-1996",
    tenGioiTinh: "Nam",
    danToc: "Kinh",
    tonGiao: "Thiên chúa",
    quocTich: "Việt Nam",
    tenDoanhNghiep:"Phương Tây smart",
    idLoaiHinh: "1",
    namThanhLap:"14-03-2000",
    vonDieuLe:"200000000000",
    nguoiLienHe:"Nguyễn Văn D",
    chucVuNguoiLienHe:"CEO",
    sdtNguoiLienHe:"09123456789",
    emailNguoiLienHe:"nguyenvana@gmail.com",
    moHinhKinhDoanhs: [
      {
        tenMoHinh: "Mô hình 2",
        tenNganhHang: "Y tế",
        thuongHieu: "Vinasin",
        tuoiTu: 19,
        tuoiDen: 29,
        doiTuongkhachHang: "Tre em",
        thuNhapTu: 12000000,
        thuNhapDen: 20000000,
        giaTrungBinhTu: 12000,
        giaTrungBinhDen: 40000,
        tenXuatXu: "Viet Nam",
        noiBatkhacBiet: "Hàng người Việt",
        tenHoSoLoaiHinh: "Hồ Sơ 1",
        tenHoSoXuatXu: "Hoa Kỳ",
        tenHoSoChungMinhNhapKhau: "Hồ Sơ chứng minh 1",
        doanhThuTrungBinhTu: 200000000,
        doanhThuTrungBinhDen: 400000000,
        dienTichToiThieu: 120,
        dienTichToiDa: 440,
        dacDiemViTri: "Ngã Tư",
        kieuGianHang: "Kiểu mặt bằng 1",
        giaThueChapNhan: 20000000,
        tenTienTe: "VND",
        tenViTriCuahang: "Ngã tư Thành Thái",
        soLuongCuaHang: 10,
        cuaHangDaCo: 12,
        cuaHangDuKien: 23,
        viTriQuanTamMoCuaHang: "Không",
        yeuCauDatBiet: "không",
        tenThoiGianThietKeTB: "1 tháng",
        tenThoiGianThiCongTB: "3 tháng",
        yeuCauMarketing: "Không",
      },
    ],
    dienTich: "120km2",
    giaThueDeNghi: "120000000",
    tenTienTe: "VND",
    thoiGianMo: "12-12-2022",
    cacVanDeKhac: "Không",
  },
  {
    id: "5",
    hoTen: "Trần Lê Hương",
    soCMND: "223431132",
    ngaySinh: "15-03-1998",
    tenGioiTinh: "Nữ",
    danToc: "Kinh",
    tonGiao: "Thiên chúa",
    quocTich: "Việt Nam",
    tenDoanhNghiep:"Phương Đông Nam smart",
    idLoaiHinh: "1",
    namThanhLap:"14-03-2000",
    vonDieuLe:"200000000000",
    nguoiLienHe:"Nguyễn Văn E",
    chucVuNguoiLienHe:"CEO",
    sdtNguoiLienHe:"09123456789",
    emailNguoiLienHe:"nguyenvana@gmail.com",
    moHinhKinhDoanhs: [
      {
        tenMoHinh: "Mô hình 2",
        tenNganhHang: "Y tế",
        thuongHieu: "Vinasin",
        tuoiTu: 19,
        tuoiDen: 29,
        doiTuongkhachHang: "Tre em",
        thuNhapTu: 12000000,
        thuNhapDen: 20000000,
        giaTrungBinhTu: 12000,
        giaTrungBinhDen: 40000,
        tenXuatXu: "Viet Nam",
        noiBatkhacBiet: "Hàng người Việt",
        tenHoSoLoaiHinh: "Hồ Sơ 1",
        tenHoSoXuatXu: "Hoa Kỳ",
        tenHoSoChungMinhNhapKhau: "Hồ Sơ chứng minh 1",
        doanhThuTrungBinhTu: 200000000,
        doanhThuTrungBinhDen: 400000000,
        dienTichToiThieu: 120,
        dienTichToiDa: 440,
        dacDiemViTri: "Ngã Tư",
        kieuGianHang: "Kiểu mặt bằng 1",
        giaThueChapNhan: 20000000,
        tenTienTe: "VND",
        tenViTriCuahang: "Ngã tư Thành Thái",
        soLuongCuaHang: 10,
        cuaHangDaCo: 12,
        cuaHangDuKien: 23,
        viTriQuanTamMoCuaHang: "Không",
        yeuCauDatBiet: "không",
        tenThoiGianThietKeTB: "1 tháng",
        tenThoiGianThiCongTB: "3 tháng",
        yeuCauMarketing: "Không",
      },
    ],
    dienTich: "120km2",
    giaThueDeNghi: "120000000",
    tenTienTe: "VND",
    thoiGianMo: "12-12-2022",
    cacVanDeKhac: "Không",
  },
];
