export const ListRoleOption = {
    HRM_0001: 'DuyetTruongDonViAsync',
    HRM_0002: 'DuyetBanTCCBAsync',
    HRM_0003: 'DuyetThongTinNhanSuNSAsync',
    HRM_0004: 'DuyetThongTinNhanSuTDAsync',
    HRM_0005: 'DuyetHopDongAsync',
    HRM_0006: 'UpdateNhatKyLuongAsync',
    HRM_0007: 'CreateNhanSuTuyenDungAsync',
    HRM_0008: 'UpdatingUserSSOAsync',
    // HRM_0009: '',
    HRM_0010: 'UpdateNhanSuVaThongTinChiTietAsync',
    HRM_0011: 'XacNhanKetQuaTuyenNhanSuAsync',
    HRM_0012: 'DuyetUngVienOnlineAsync',
    HRM_0013: 'DuyetDonViDonChuyenCDNNAsync',
    HRM_0014: 'DuyetDHQGHNChuyenCDNNAsync',
    HRM_0015: 'DuyetHoiDongDonViDonChuyenCDNNAsync',
    HRM_0016: 'DuyetHoiDongDHQGHNDonChuyenCDNNAsync',

    NBL_0001: 'DongBoNhanSuNangBacLuongAsync',

    DGNS_0001: 'YKienThamMuuBanTCCB',

    PTN_0001: 'DuyetDangKySuDungAsync',
    PTN_0002: 'DuyetTB_MangRaNgoaiAsync',
    PTN_0003: 'IsQuyenBanKHCNTheoLoaiHinh',
    PTN_0004: 'IsQuyenBanKHCNTheoLinhVuc',
    PTN_0005: 'IsQuyenPhongKHCNLuanAnLuanVan',
    PTN_0006: 'IsQuyenPhongKHCNBaiThucHanh',
    PTN_0007: 'IsQuyenPhongKHCNBaoCaoKhoaHoc',
    PTN_0008: 'IsQuyenPhongKHCNBaiBaoKhoaHoc',
    PTN_0009: 'IsQuyenPhongKHCNNhiemVuKhoaHoc',
    PTN_0010: 'IsQuyenPhongKHCNHoiNghiHoiThao',
    PTN_0011: 'IsQuyenPhongKHCNHopDongKhaiThac',
    PTN_0012: 'IsQuyenPhongKHCNSoHuuTriTue',
    PTN_0013: 'IsQuyenPhongKHCNSanPhamKHCN',
    PTN_0014: 'IsQuyenPhongKHCNHieuQuaSuDung',
    PTN_0015: 'CreateDoiNguCanBoAsync',
    PTN_0016: 'UpdateDoiNguCanBoAsync',
    PTN_0017: 'DeleteDoiNguCanBoAsync',
    PTN_0018: 'GetDoiNguCanBoByIdAsync',

    PTN_0020: 'TinhKhauHaoThietBi',
    PTN_0021: 'KhoaDotKhauHao',

    PTN_0022: 'CreateNhomNghienCuuAsync',
    PTN_0023: 'UpdateNhomNghienCuuAsync',
    PTN_0024: 'DeleteNhomNghienCuuAsync',
    PTN_0025: 'GetNhomNghienCuuByIdAsync',

    PTN_0026: 'CreateHopDongKhaiThacAsync',
    PTN_0027: 'UpdateHopDongKhaiThacAsync',
    PTN_0028: 'DeleteHopDongKhaiThacAsync',
    PTN_0029: 'GetHopDongKhaiThacByIdAsync',

    PTN_0030: 'CreateBaiThucHanhThiNghiemAsync',
    PTN_0031: 'UpdateBaiThucHanhThiNghiemAsync',
    PTN_0032: 'DeleteBaiThucHanhThiNghiemAsync',
    PTN_0033: 'GetBaiThucHanhThiNghiemByIdAsync',

    PTN_0034: 'CreateDoiTacThucHienAsync',
    PTN_0035: 'UpdateDoiTacThucHienAsync',
    PTN_0036: 'DeleteDoiTacThucHienAsync',
    PTN_0037: 'GetDoiTacThucHienByIdAsync',

    PTN_0038: 'GetDataListAsync',

    PTN_0039: 'CreateKH_KeHoachAsync',
    PTN_0040: 'UpdateKH_KeHoachAsync',
    PTN_0041: 'DeleteKH_KeHoachAsync',
    PTN_0042: 'GetKH_KeHoachByIdAsync',

    PTN_0043: 'CreateTB_ThietBiAsync',
    PTN_0044: 'UpdateTB_ThietBiAsync',
    PTN_0045: 'DeleteTB_ThietBiAsync',
    PTN_0046: 'GetTB_ThietBiByIdAsync',
    PTN_0047: 'GetDanhSachThietBiAsync',

    PTN_0060: 'IsBanKHCNBaoCaoChiTieuKeHoach',

    KHCN_0001: 'BaiBaoKhoaHocChangeStatusAsync',
    KHCN_0002: 'BaoCaoKhoaHocChangeStatusAsync',
    KHCN_0003: 'DuAnDauTuChangeStatusAsync',
    KHCN_0004: 'GiaiThuongKHCNChangeStatusAsync',
    KHCN_0005: 'HoiThaoHoiNghiChangeStatusAsync',
    KHCN_0006: 'PhatMinhSangCheChangeStatusAsync',
    KHCN_0007: 'NhiemVuKhoaHocChangeStatusAsync',
    KHCN_0008: 'SachChuyenKhaoChangeStatusAsync',
    KHCN_0009: 'SanPhamDaoTaoChangeStatusAsync',
    KHCN_0010: 'ExportExcel',
    KHCN_0011: 'AddKinhPhiThucHien',
    KHCN_0012: 'AddKinhPhiThucHienDuAn',
    KHCN_0013: 'DVCreateKH_PhanCongThucHienAsync',
    KHCN_0014: 'DonViTongHopDuLieuAsync',
    KHCN_0015: 'BanTongHopDuLieuAsync',
    KHCN_0016: 'IsBanKHCNBieuDoTongHop',
    KHCN_0017: 'IsBanKHCNBieuDoBaiBao',
    KHCN_0018: 'IsBanKHCNBieuDoSachChuyenKhao',
    KHCN_0019: 'IsBanKHCNBieuDoSoHuuTriTue',
};
